export default [
	{
		"cid": 1763, // 客户id
		"oid": 6268, // 订单id
		"product_id": 3299, // 商品ID
		"product_name": "a2奶粉", // 商品名
		"nickname": "gogo", // 客户昵称
		"quantity": 5, // 数量
		"status": 1, // 状态 是否付款
		"remark": "hahah", // 备注
		"unit_cost": null, // 成本
		"unit_price": null, // 价格
		"mail_free": 0, // 包邮
        "mail_pay": 0, // 邮费
		"room_id": "888888", // 房间id what is this?
		"exchange_rate": 0.88, // 汇率
		"discount": 1, // 折扣
		"cate_id": 44, //
		"cate_name": "1号街道", // 地点名
		"sendoff": 0, // 是否发货

        /*******************新添加信息*******************/

        "deposit": null, //定金
        "mail_address": { // 地址信息
            "name": '陈帅哥',
            "phone": '123123123',
            "address": '安徽',
        },

        /*******************新添加信息1*******************/

        "finish_date": '2017-04-18',//完成时间
	},
	{
		"cid": 555,
		"oid": 6267,
		"product_id": 3299,
		"product_name": "a2奶粉",
		"nickname": "jjxf",
		"quantity": 1,
		"status": 1,
		"remark": "hahah",
		"unit_cost": 80,
		"unit_price": 500,
		"mail_free": 0,
		"mail_pay": 0,
		"room_id": "888888",
		"exchange_rate": 0.88,
		"discount": 1,
		"cate_id": 44,
		"cate_name": "1号街道",
		"sendoff": 0,

        "finish_date": '2017-04-19',
	},
	{
		"cid": 29,
		"oid": 6161,
		"product_id": 3299,
		"product_name": "a2奶粉",
		"nickname": "SHU",
		"quantity": 11,
		"status": 1,
		"remark": "",
		"unit_cost": 250,
		"unit_price":300,
		"mail_free": 0,
		"mail_pay": 0,
		"room_id": "888888",
		"exchange_rate": 0.88,
		"discount": 1,
		"cate_id": 44,
		"cate_name": "1号街道",
		"sendoff": 0,

        "finish_date": '2017-04-19',
	},
    {
        "cid": 29,
        "oid": 6169,
        "product_id": 3299,
        "product_name": "a2奶粉",
        "nickname": "SHU",
        "quantity": 1,
        "status": 1,
        "remark": "",
        "unit_cost": 1,
        "unit_price": 5000,
        "mail_free": 0,
        "mail_pay": 5000,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 44,
        "cate_name": "1号街道",
        "sendoff": 0,

        "finish_date": '2017-04-19',
    },
    {
        "cid": 1059,
        "oid": 6165,
        "product_id": 1374,
        "product_name": "mac pro8",
        "nickname": "疯叔叔",
        "quantity": 1,
        "status": 1,
        "remark": "",
        "unit_cost": null,
        "unit_price": null,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 44,
        "cate_name": "1号街道",
        "sendoff": 0,

        "finish_date": '2017-04-18',
    },
    {
        "cid": 614,
        "oid": 1986,
        "product_id": 1559,
        "product_name": "乌骓马",
        "nickname": "我来也",
        "quantity": 1,
        "status": 1,
        "remark": "头可破，血可流，我来也精神要长留",
        "unit_cost": null,
        "unit_price": null,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 44,
        "cate_name": "1号街道",
        "sendoff": 0,

        "finish_date": '2017-04-20',
    },
    {
        "cid": 1769,
        "oid": 6275,
        "product_id": 3785,
        "product_name": "dddd",
        "nickname": "eeee",
        "quantity": 7,
        "status": 1,
        "remark": "ffff",
        "unit_cost": null,
        "unit_price": null,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 444,
        "oid": 6270,
        "product_id": 1311,
        "product_name": "quchengshiyagao",
        "nickname": "糖糖",
        "quantity": 7,
        "status": 1,
        "remark": "hahah",
        "unit_cost": 12,
        "unit_price": 23,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 214,
        "oid": 12979,
        "product_id": 777,
        "product_name": "后台上传测试title",
        "nickname": "困死了",
        "quantity": 1,
        "status": 1,
        "remark": "",
        "unit_cost": null,
        "unit_price": null,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 847,
        "oid": 12978,
        "product_id": 7642,
        "product_name": "测试一下加单",
        "nickname": "测试用户8",
        "quantity": 14,
        "status": 1,
        "remark": "",
        "unit_cost": null,
        "unit_price": null,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 8477,
        "oid": 6666,
        "product_id": 444,
        "product_name": "测试",
        "nickname": "测试",
        "quantity": 14,
        "status": 0,
        "remark": "",
        "unit_cost": 12,
        "unit_price": 123,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,
        "deposit": 100,

        "finish_date": '2017-04-01',
    },
    {
        "cid": 8847,
        "oid": 6666,
        "product_id": 444,
        "product_name": "测试",
        "nickname": "测试",
        "quantity": 14,
        "status": 0,
        "remark": "",
        "unit_cost": 12,
        "unit_price": 123,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,
        "deposit": 100,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 8447,
        "oid": 6666,
        "product_id": 444,
        "product_name": "测试",
        "nickname": "测试",
        "quantity": 14,
        "status": 0,
        "remark": "",
        "unit_cost": 12,
        "unit_price": 123,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,
        "deposit": 100,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 84747,
        "oid": 6666,
        "product_id": 444,
        "product_name": "测试",
        "nickname": "测试",
        "quantity": 14,
        "status": 0,
        "remark": "",
        "unit_cost": 12,
        "unit_price": 123,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,
        "deposit": 100,

        "finish_date": '2017-04-22',
    },
    {
        "cid": 847847,
        "oid": 6666,
        "product_id": 444,
        "product_name": "测试",
        "nickname": "测试",
        "quantity": 14,
        "status": 0,
        "remark": "",
        "unit_cost": 12,
        "unit_price": 123,
        "mail_free": 0,
        "mail_pay": 0,
        "room_id": "888888",
        "exchange_rate": 0.88,
        "discount": 1,
        "cate_id": 1,
        "cate_name": "default",
        "sendoff": 0,
        "deposit": 100,

        "finish_date": '2017-04-22',
    }
]